# Generated by Django 4.1 on 2023-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_photo_yummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='yummy_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
