# Generated by Django 4.1 on 2023-06-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_yummy_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='thumbs_up',
        ),
    ]
